<#
.SYNOPSIS
Compare GPO XML exports generated by Get-GPOReport.

.DESCRIPTION
Processes one or more GPO XML exports and generates comparison, inventory,
conflict, duplicate, deprecated-policy and Intune migration reports.

XML parsing is performed by GPOCompare.psm1. This script:
- Loads the XML files and calls Get-GPOSettingsFromXml
- Builds the comparison maps
- Generates and exports the CSV reports

Settings are compared case-insensitively. Firewall rules are exported only to
FirewallRules.csv; firewall profile settings are part of the normal comparison.

Reports written to OutputFolder:

ParsedSettings.csv
    Every parsed setting (raw parser output).

CommonSettings.csv
    Exact match: identical Class, Extension, Category, SettingName, Value and
    State in every GPO.

CommonSettingsByName.csv
    Setting configured in every GPO regardless of value.
    SameValueEverywhere = False means the values differ between GPOs.

UniqueSettings.csv
    Setting configured in some GPOs but not all. One row per distinct value;
    PresentIn lists the GPOs that use that value. ValuesDiffer = True means the
    GPOs that do configure it disagree.

ConflictingSettings.csv
    Setting configured in more than one GPO with different values. A GPO that
    has several rows for one setting is compared as a set of values.

DuplicateSettings.csv
    Setting configured identically in more than one GPO (PresentIn).

DeprecatedPolicies.csv
    Settings that match DeprecatedPoliciesReference.md.

MissingSettingsMatrix.csv
    Present / Missing per GPO for every setting name.

FirewallRules.csv
    Inventory of firewall rules (Inbound and Outbound).

IntuneMigrationCandidates.csv
    Every setting with its Intune mapping from the mapping file, plus a
    Deprecated flag. MappingStatus is one of the values defined in the mapping
    file, or Unmapped (no matching entry) or MappingFileMissing.

UnclassifiedSettings.csv
    Unsupported extensions or sections, settings without a name, and parser
    errors. Anything listed here is NOT part of the comparison reports.

ParserFailures.csv
    XML files that could not be parsed at all. Those GPOs are excluded from
    the GPO total.

RunStatistics.csv
    Counts for the run. Every other report has a count here that equals its
    number of rows (for example Conflicts for ConflictingSettings.csv).

GPOCompareXml.xlsx (only with -OutputFormat Excel)
    One workbook, written instead of the CSV files, with one worksheet per
    report in this order: RunStatistics, CommonSettings, UniqueSettings,
    DeprecatedPolicies, FirewallRules, IntuneMigrationCandidates,
    DuplicateSettings, ConflictingSettings, ParsedSettings, then the others.
    Every worksheet is an Excel table with a blue header (table style
    Medium2) and a frozen header row. RunStatistics is shown as a
    Statistic / Value table; each statistic that counts a worksheet's rows
    is a link to that worksheet. Text values are stored exactly as text;
    counts are numbers and True/False values are Excel TRUE/FALSE.

.PARAMETER XmlFolder
Folder containing XML exports (Get-GPOReport -ReportType Xml).

.PARAMETER OutputFolder
Folder where generated reports are written. Created if it does not exist.

.PARAMETER ModulePath
Path to GPOCompare.psm1. Default: next to this script.

.PARAMETER IntuneMappingPath
Path to the Intune mapping file. Default: intunemapping.json next to this
script. The file is optional: if it does not exist a warning is shown and the
run continues (mapping columns show MappingFileMissing). A file that exists
but cannot be parsed stops the run.

.PARAMETER DeprecatedReferencePath
Path to DeprecatedPoliciesReference.md. Default: next to this script. If it
does not exist a warning is shown and no deprecated matches are reported.

.PARAMETER FilePrefix
Text added to the start of every output file name, followed by a hyphen.
For example, LS writes LS-CommonSettings.csv instead of CommonSettings.csv.
If this parameter is not given, the script asks for the prefix; press Enter
for no prefix. Pass -FilePrefix "" to skip the question and use no prefix.
In a session that cannot ask (for example -NonInteractive), no prefix is
used.

.PARAMETER OutputFormat
CSV or Excel. CSV writes one CSV file per report. Excel writes one workbook,
GPOCompareXml.xlsx (with the file name prefix, if one is used), with one worksheet
per report and no CSV files. If this parameter is not given, the script
asks (C or E; press Enter for CSV). In a session that cannot ask (for
example -NonInteractive), CSV is used.

Excel output needs the ImportExcel module; Excel itself is not needed. If
the module is not installed, the script installs it for the current user
from the PowerShell Gallery (Install-Module ImportExcel -Scope CurrentUser,
plus the NuGet package provider if missing). If it cannot be installed, a
warning is shown and the output continues as CSV files. If the workbook
cannot be written (for example, the file is open in Excel), the reports are
written as CSV files instead. A value longer than 32767 characters (the
Excel cell limit) is cut to that length in the workbook, with a warning.

.EXAMPLE
.\Compare-GPOXml.ps1 -XmlFolder "C:\GPOProject\XML" -OutputFolder "C:\GPOProject\Output"

.EXAMPLE
.\Compare-GPOXml.ps1 -XmlFolder "C:\GPOProject\XML" -OutputFolder "C:\GPOProject\Output" -FilePrefix LS

.EXAMPLE
.\Compare-GPOXml.ps1 -XmlFolder "C:\GPOProject\XML" -OutputFolder "C:\GPOProject\Output" -FilePrefix LS -OutputFormat Excel

.NOTES
Author:  Siconic
Version: 4.0

Versioning: MAJOR bumps mean restructured logic, a changed CSV/report
schema (something that could break a workflow built on the old output), or
a major new feature such as a new output format. MINOR bumps are bug fixes
and small additions that don't change existing columns or behavior.
GPOCompare.psm1 is versioned in lockstep with this script, since the two are always used together.

Changelog:
  4.0 - Excel output. New -OutputFormat parameter (CSV or Excel); if it
        is not given, the script asks. Excel writes one workbook,
        GPOCompareXml.xlsx, with one worksheet per report and no CSV
        files. Worksheet order: RunStatistics, CommonSettings,
        UniqueSettings, DeprecatedPolicies, FirewallRules,
        IntuneMigrationCandidates, DuplicateSettings, ConflictingSettings,
        ParsedSettings, then the others. Every worksheet is a blue
        (Medium2) Excel table. RunStatistics is a Statistic / Value table
        whose statistics link to their worksheets. RunStatistics.csv has
        new columns at the end (MissingSettingsMatrix,
        IntuneMigrationCandidates), so every report has
        a count. If the ImportExcel
        module is missing, the script installs it for the current user;
        if that fails, or the workbook cannot be written, the output is
        CSV files. No module changes; the module version is kept in
        lockstep.
  3.3 - New -FilePrefix parameter. The prefix and a hyphen are added to
        the start of every output file name (LS-CommonSettings.csv). If
        the parameter is not given, the script asks for it; an empty
        answer keeps the original file names. No module changes; the
        module version is kept in lockstep.
  3.2 - GPOCompare.psm1: replaced all 13 uses of the "{0}={1}" -f
        composite-format operator with plain string interpolation, which
        cannot throw the "index (zero based)..." formatting exception that
        was reported against 3.1.
  3.1 - GPOCompare.psm1: unsupported-extension Unclassified rows now carry
        a SettingName, Value, and State per item instead of one blank row
        per extension; parser-error Reason text now includes the module
        line number that threw.
  3.0 - Full rework: sorted list comparisons, GPO total based on parsed
        files, conflict/unique/duplicate rules fixed, Intune mapping and
        deprecated-policy matching added, Unclassified safety net added
        for unsupported extensions and Security sub-sections.

Recommended layout:

    GPO Project
        Compare-GPOXml.ps1
        GPOCompare.psm1
        intunemapping.json
        DeprecatedPoliciesReference.md
        XML\
        Output\

After a run, check Unclassified and ParseFailures in RunStatistics.csv. Both
should be 0 before the comparison reports are treated as complete.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$XmlFolder,

    [Parameter(Mandatory)]
    [string]$OutputFolder,

    [string]$ModulePath = (Join-Path $PSScriptRoot "GPOCompare.psm1"),

    [string]$IntuneMappingPath = (Join-Path $PSScriptRoot "intunemapping.json"),

    [string]$DeprecatedReferencePath = (Join-Path $PSScriptRoot "DeprecatedPoliciesReference.md"),

    [string]$FilePrefix,

    [ValidateSet('CSV', 'Excel')]
    [string]$OutputFormat
)

$ErrorActionPreference = "Stop"

# Separator used when building comparison keys. It cannot occur in setting text.
$Sep = [string][char]0x1F

# Every report this script writes. The Excel workbook uses this order for
# its worksheets.
$ExpectedReports = @(
    "RunStatistics.csv"
    "CommonSettings.csv"
    "UniqueSettings.csv"
    "DeprecatedPolicies.csv"
    "FirewallRules.csv"
    "IntuneMigrationCandidates.csv"
    "DuplicateSettings.csv"
    "ConflictingSettings.csv"
    "ParsedSettings.csv"
    "CommonSettingsByName.csv"
    "MissingSettingsMatrix.csv"
    "UnclassifiedSettings.csv"
    "ParserFailures.csv"
)

# RunStatistics value -> the worksheet whose rows it counts. In the Excel
# workbook, these statistics are links to their worksheet. Every worksheet
# except RunStatistics has one.
$StatisticWorksheets = @{
    Settings                  = "ParsedSettings"
    FirewallRules             = "FirewallRules"
    CommonSettings            = "CommonSettings"
    CommonByName              = "CommonSettingsByName"
    UniqueSettings            = "UniqueSettings"
    Conflicts                 = "ConflictingSettings"
    Duplicates                = "DuplicateSettings"
    Deprecated                = "DeprecatedPolicies"
    Unclassified              = "UnclassifiedSettings"
    ParseFailures             = "ParserFailures"
    MissingSettingsMatrix     = "MissingSettingsMatrix"
    IntuneMigrationCandidates = "IntuneMigrationCandidates"
}

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

if (-not (Test-Path -LiteralPath $XmlFolder -PathType Container))
{
    throw "XML folder not found: $XmlFolder"
}

if (-not (Test-Path -LiteralPath $ModulePath -PathType Leaf))
{
    throw "Module not found: $ModulePath"
}

if (-not (Test-Path -LiteralPath $OutputFolder))
{
    New-Item -Path $OutputFolder -ItemType Directory -Force | Out-Null
}

$OutputFolder = (Resolve-Path -LiteralPath $OutputFolder).ProviderPath

# ------------------------------------------------------------
# Output file name prefix
# ------------------------------------------------------------

# When -FilePrefix is not given, ask for it. An empty answer means no
# prefix. In a non-interactive session Read-Host fails, and no prefix is
# used.
if (-not $PSBoundParameters.ContainsKey('FilePrefix'))
{
    try
    {
        $FilePrefix = Read-Host "Output file name prefix (for example LS). Press Enter for no prefix"
    }
    catch
    {
        $FilePrefix = ""
    }
}

$FilePrefix = "$($FilePrefix)".Trim().TrimEnd('-')

if ($FilePrefix.IndexOfAny([System.IO.Path]::GetInvalidFileNameChars()) -ge 0)
{
    throw "FilePrefix contains a character that is not allowed in a file name: $FilePrefix"
}

# Added to the start of every output file name, for example "LS-".
$FileNamePrefix = ""

if ($FilePrefix -ne "")
{
    $FileNamePrefix = "$($FilePrefix)-"
    Write-Host "Output file prefix: $FileNamePrefix"
}
else
{
    Write-Host "Output file prefix: (none)"
}

# ------------------------------------------------------------
# Output format (CSV files or Excel workbook)
# ------------------------------------------------------------

# When -OutputFormat is not given, ask for it. An empty answer means CSV.
# In a non-interactive session Read-Host fails, and CSV is used.
if (-not $PSBoundParameters.ContainsKey('OutputFormat'))
{
    $Answer = ""

    try
    {
        $Answer = Read-Host "Output format: C = CSV files, E = Excel workbook. Press Enter for CSV"
    }
    catch
    {
        $Answer = ""
    }

    $Answer = "$($Answer)".Trim()

    if (($Answer -ieq 'E') -or ($Answer -ieq 'Excel'))
    {
        $OutputFormat = 'Excel'
    }
    elseif (($Answer -eq '') -or ($Answer -ieq 'C') -or ($Answer -ieq 'CSV'))
    {
        $OutputFormat = 'CSV'
    }
    else
    {
        Write-Warning "'$Answer' is not C or E. Output will be CSV files."
        $OutputFormat = 'CSV'
    }
}

# Excel output needs the ImportExcel module. If it is not installed, try to
# install it for the current user from the PowerShell Gallery. If that
# fails, the output continues as CSV files.
if ($OutputFormat -eq 'Excel')
{
    $ImportExcelReady = (@(Get-Module -ListAvailable -Name ImportExcel).Count -gt 0)

    if (-not $ImportExcelReady)
    {
        Write-Host "The ImportExcel module is not installed. Installing it for the current user from the PowerShell Gallery..."

        try
        {
            # The PowerShell Gallery requires TLS 1.2, which Windows
            # PowerShell 5.1 does not always use by default.
            [System.Net.ServicePointManager]::SecurityProtocol =
                [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12

            # Install-Module needs the NuGet package provider.
            if (@(Get-PackageProvider -ListAvailable -Name NuGet -ErrorAction SilentlyContinue).Count -eq 0)
            {
                Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Scope CurrentUser -Force -ErrorAction Stop | Out-Null
            }

            # -Force skips the question about installing from an untrusted
            # repository (the PowerShell Gallery is untrusted by default).
            Install-Module -Name ImportExcel -Repository PSGallery -Scope CurrentUser -Force -ErrorAction Stop
        }
        catch
        {
            Write-Warning "Installing the ImportExcel module failed: $($_.Exception.Message)"
        }

        $ImportExcelReady = (@(Get-Module -ListAvailable -Name ImportExcel).Count -gt 0)

        if ($ImportExcelReady)
        {
            Write-Host "The ImportExcel module is available."
        }
    }

    if ($ImportExcelReady)
    {
        try
        {
            Import-Module ImportExcel -ErrorAction Stop
        }
        catch
        {
            Write-Warning "Loading the ImportExcel module failed: $($_.Exception.Message)"
            $ImportExcelReady = $false
        }
    }

    if (-not $ImportExcelReady)
    {
        Write-Warning "The ImportExcel module could not be installed. Output will continue as CSV files."
        $OutputFormat = 'CSV'
    }
}

$ExcelOutput  = ($OutputFormat -eq 'Excel')
$WorkbookName = "$($FileNamePrefix)GPOCompareXml.xlsx"
$WorkbookPath = Join-Path $OutputFolder $WorkbookName

if ($ExcelOutput)
{
    Write-Host "Output format: Excel workbook ($WorkbookName)"
}
else
{
    Write-Host "Output format: CSV files"
}

# Reports collected by Export-Report for the Excel workbook.
$ExcelSheets = [System.Collections.ArrayList]::new()

# ------------------------------------------------------------
# Helper Functions
# ------------------------------------------------------------

function Export-Report
{
    param(
        [AllowNull()]
        [object]$Data,

        [Parameter(Mandatory)]
        [string]$Name
    )

    $Rows = @()

    if ($null -ne $Data)
    {
        $Rows = @($Data)
    }

    # Excel output: keep the rows for the workbook, which is written by
    # Save-ExcelOutput. No CSV file is written.
    if ($ExcelOutput)
    {
        [void]$ExcelSheets.Add(
            [PSCustomObject]@{
                Name = [System.IO.Path]::GetFileNameWithoutExtension($Name)
                Rows = $Rows
            }
        )

        return
    }

    Write-CsvReport -Rows $Rows -Name $Name
}

function Write-CsvReport
{
    param(
        [AllowNull()]
        [object[]]$Rows,

        [Parameter(Mandatory)]
        [string]$Name
    )

    $Path = Join-Path $OutputFolder "$($FileNamePrefix)$($Name)"

    if ($null -eq $Rows)
    {
        $Rows = @()
    }

    # Export-Csv writes nothing for empty input; create an empty file instead
    # so every report exists.
    if ($Rows.Count -eq 0)
    {
        [System.IO.File]::WriteAllText($Path, "")
        return
    }

    $Rows |
    Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8
}

function Get-ReportLocation
{
    param(
        [Parameter(Mandatory)]
        [string]$Name
    )

    # Where a report can be found, for messages: its CSV file, or its
    # worksheet in the Excel workbook.
    if ($ExcelOutput)
    {
        return "the $([System.IO.Path]::GetFileNameWithoutExtension($Name)) worksheet in $WorkbookName"
    }

    return "$($FileNamePrefix)$($Name)"
}

function Save-ExcelOutput
{
    # Writes the reports collected by Export-Report to the Excel workbook,
    # with the worksheets in $ExpectedReports order. After an early stop,
    # only the reports collected so far are included. If the workbook
    # cannot be written, the same reports are written as CSV files instead.
    $OrderedSheets = [System.Collections.ArrayList]::new()

    foreach ($Report in $ExpectedReports)
    {
        $SheetName = [System.IO.Path]::GetFileNameWithoutExtension($Report)

        foreach ($Sheet in @($ExcelSheets | Where-Object { $_.Name -eq $SheetName }))
        {
            [void]$OrderedSheets.Add($Sheet)
        }
    }

    try
    {
        Export-ExcelWorkbook -Path $WorkbookPath -Sheets @($OrderedSheets)
    }
    catch
    {
        Write-Warning "Writing the Excel workbook failed: $($_.Exception.Message). Writing CSV files instead."

        # Remove a partly written workbook. If it is locked (for example,
        # open in Excel), leave it and continue with the CSV files.
        try
        {
            if (Test-Path -LiteralPath $WorkbookPath)
            {
                Remove-Item -LiteralPath $WorkbookPath -Force -ErrorAction Stop
            }
        }
        catch
        {
        }

        $script:ExcelOutput = $false

        foreach ($Sheet in $OrderedSheets)
        {
            Write-CsvReport -Rows @($Sheet.Rows) -Name "$($Sheet.Name).csv"
            Write-Host "[OK] $($FileNamePrefix)$($Sheet.Name).csv"
        }

        return
    }

    if (Test-Path -LiteralPath $WorkbookPath)
    {
        Write-Host "[OK] $WorkbookName ($($OrderedSheets.Count) worksheets)"
    }
    else
    {
        Write-Warning "$WorkbookName missing"
    }
}

function ConvertTo-ExcelSheetRows
{
    param(
        [AllowNull()]
        [object[]]$Rows
    )

    # An Excel cell holds at most 32767 characters. Longer values are cut to
    # that length in the workbook only; the CSV files keep the full value.
    $MaxCellLength = 32767

    $Output    = [System.Collections.ArrayList]::new()
    $Truncated = 0

    # Export-Excel writes any text that starts with "=" as a formula, and has
    # no option to turn this off. These cells are recorded here so that
    # Export-ExcelWorkbook can write their text back as plain text.
    $TextCells = [System.Collections.ArrayList]::new()

    # Row 1 of the worksheet is the header row.
    $RowNumber = 1

    foreach ($Row in @($Rows))
    {
        $RowNumber++
        $ColumnNumber = 0
        $Copy = [ordered]@{}

        foreach ($Property in $Row.PSObject.Properties)
        {
            $ColumnNumber++
            $Value = $Property.Value

            if (($Value -is [string]) -and ($Value.Length -gt $MaxCellLength))
            {
                $Value = $Value.Substring(0, $MaxCellLength)
                $Truncated++
            }

            if (($Value -is [string]) -and $Value.StartsWith('='))
            {
                [void]$TextCells.Add(
                    [PSCustomObject]@{
                        Row    = $RowNumber
                        Column = $ColumnNumber
                        Value  = $Value
                    }
                )
            }

            $Copy[$Property.Name] = $Value
        }

        [void]$Output.Add([PSCustomObject]$Copy)
    }

    return [PSCustomObject]@{
        Rows      = $Output
        Truncated = $Truncated
        TextCells = $TextCells
    }
}

function Export-RunStatisticsSheet
{
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [AllowNull()]
        [object[]]$Rows,

        # Names of the worksheets in the workbook. A statistic is a link only
        # when its worksheet is one of these.
        [AllowNull()]
        [string[]]$WorksheetNames
    )

    # RunStatistics.csv is one row with one column per count. In the
    # workbook it is shown as a two-column table (Statistic, Value) with a
    # title and a blue table style, which is easier to read. The CSV file
    # keeps the original layout.
    $TableRows = [System.Collections.ArrayList]::new()

    foreach ($Row in @($Rows))
    {
        foreach ($Property in $Row.PSObject.Properties)
        {
            $Value = $Property.Value

            # Same text as in the CSV file.
            if ($Value -is [datetime])
            {
                $Value = $Value.ToString()
            }

            [void]$TableRows.Add(
                [PSCustomObject]@{
                    Statistic = $Property.Name
                    Value     = $Value
                }
            )
        }
    }

    $Package = $TableRows |
        Export-Excel -Path $Path -WorksheetName 'RunStatistics' -Title 'Run Statistics' -TitleBold -TitleSize 14 -TableName 'RunStatisticsTable' -TableStyle Medium2 -AutoSize -NoNumberConversion '*' -NoHyperLinkConversion '*' -PassThru

    # Left-align the Value column so the timestamp and the counts line up.
    $Worksheet = $Package.Workbook.Worksheets['RunStatistics']
    $Worksheet.Column(2).Style.HorizontalAlignment = [OfficeOpenXml.Style.ExcelHorizontalAlignment]::Left

    # Make each statistic that counts a worksheet's rows a link to that
    # worksheet. Row 1 is the title, row 2 the table header, so the first
    # statistic is on row 3.
    $RowNumber = 2

    foreach ($TableRow in $TableRows)
    {
        $RowNumber++
        $Target = $StatisticWorksheets[$TableRow.Statistic]

        if (($null -eq $Target) -or (@($WorksheetNames) -notcontains $Target))
        {
            continue
        }

        $Cell           = $Worksheet.Cells[$RowNumber, 1]
        $Cell.Hyperlink = [OfficeOpenXml.ExcelHyperLink]::new("'$($Target)'!A1", $TableRow.Statistic)
        $Cell.Style.Font.UnderLine = $true
        $Cell.Style.Font.Color.SetColor([System.Drawing.Color]::FromArgb(5, 99, 193))
    }

    Close-ExcelPackage -ExcelPackage $Package
}

function Export-ExcelWorkbook
{
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [AllowNull()]
        [object[]]$Sheets
    )

    # Export-Excel adds worksheets to an existing workbook, so remove the
    # workbook from any earlier run first.
    if (Test-Path -LiteralPath $Path)
    {
        Remove-Item -LiteralPath $Path -Force
    }

    $TotalTruncated = 0

    foreach ($Sheet in @($Sheets))
    {
        if (($Sheet.Name -eq 'RunStatistics') -and (@($Sheet.Rows).Count -gt 0))
        {
            Export-RunStatisticsSheet -Path $Path -Rows @($Sheet.Rows) -WorksheetNames @(@($Sheets) | ForEach-Object { $_.Name })
            continue
        }

        $SheetRows = @($Sheet.Rows)
        $TextCells = @()

        if ($SheetRows.Count -eq 0)
        {
            $SheetRows = @([PSCustomObject]@{ Result = "No rows" })
        }
        else
        {
            $Converted       = ConvertTo-ExcelSheetRows -Rows $SheetRows
            $SheetRows       = @($Converted.Rows)
            $TextCells       = @($Converted.TextCells)
            $TotalTruncated += $Converted.Truncated
        }

        # Every worksheet is an Excel table with the same blue style as the
        # RunStatistics worksheet. A table has its own filter buttons.
        # -NoNumberConversion and -NoHyperLinkConversion keep every value as
        # text, as in the CSV files.
        $Package = $SheetRows |
            Export-Excel -Path $Path -WorksheetName $Sheet.Name -TableName "$($Sheet.Name)Table" -TableStyle Medium2 -FreezeTopRow -AutoSize -NoNumberConversion '*' -NoHyperLinkConversion '*' -PassThru

        # Write text that starts with "=" back as plain text instead of a
        # formula.
        $Worksheet = $Package.Workbook.Worksheets[$Sheet.Name]

        foreach ($TextCell in $TextCells)
        {
            $Cell         = $Worksheet.Cells[$TextCell.Row, $TextCell.Column]
            $Cell.Formula = ""
            $Cell.Value   = $TextCell.Value
        }

        Close-ExcelPackage -ExcelPackage $Package
    }

    if ($TotalTruncated -gt 0)
    {
        Write-Warning "$TotalTruncated value(s) were longer than 32767 characters and were cut to that length in the Excel workbook. The CSV files have the full values."
    }
}

function Import-IntuneMapping
{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf))
    {
        Write-Warning "Intune mapping file not found: $Path - continuing without Intune mapping (MappingStatus will be MappingFileMissing)."
        return $null
    }

    try
    {
        $Catalog =
            Get-Content -LiteralPath $Path -Raw -Encoding UTF8 -ErrorAction Stop |
            ConvertFrom-Json -ErrorAction Stop
    }
    catch
    {
        throw "Failed to load Intune mapping file '$Path': $($_.Exception.Message)"
    }

    if ($null -eq $Catalog -or $null -eq $Catalog.mappings)
    {
        throw "Invalid Intune mapping file '$Path': missing 'mappings' array."
    }

    return $Catalog
}

function Test-IntuneMappingField
{
    param(
        [AllowNull()]
        [object]$Expected,

        [AllowNull()]
        [object]$Actual
    )

    if (
        $null -eq $Expected -or
        [string]::IsNullOrWhiteSpace([string]$Expected) -or
        [string]$Expected -eq '*'
    )
    {
        return $true
    }

    return ([string]$Expected -ieq [string]$Actual)
}

$script:IntuneMappingCache = @{}

function Get-IntuneMapping
{
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object]$Setting,

        [AllowNull()]
        [object]$Catalog
    )

    if ($null -eq $Catalog)
    {
        return $null
    }

    $CacheKey =
        @($Setting.Class, $Setting.Extension, $Setting.Category, $Setting.SettingName) -join $Sep

    if ($script:IntuneMappingCache.ContainsKey($CacheKey))
    {
        return $script:IntuneMappingCache[$CacheKey]
    }

    # The most specific matching entry wins (most fields that are not "*").
    # On a tie the entry that comes first in the file wins.
    $Best            = $null
    $BestSpecificity = -1

    foreach ($Map in @($Catalog.mappings))
    {
        if (
            (Test-IntuneMappingField $Map.class $Setting.Class) -and
            (Test-IntuneMappingField $Map.extension $Setting.Extension) -and
            (Test-IntuneMappingField $Map.category $Setting.Category) -and
            (Test-IntuneMappingField $Map.settingName $Setting.SettingName)
        )
        {
            $Specificity = 0

            foreach ($Field in @('class', 'extension', 'category', 'settingName'))
            {
                $FieldValue = [string]$Map.$Field

                if (-not [string]::IsNullOrWhiteSpace($FieldValue) -and $FieldValue -ne '*')
                {
                    $Specificity++
                }
            }

            if ($Specificity -gt $BestSpecificity)
            {
                $Best            = $Map
                $BestSpecificity = $Specificity
            }
        }
    }

    $script:IntuneMappingCache[$CacheKey] = $Best

    return $Best
}

# ------------------------------------------------------------
# Load Module and Reference Data
# ------------------------------------------------------------

Import-Module -Name $ModulePath -Force

Import-DeprecatedPolicyReference `
    -Path $DeprecatedReferencePath

$IntuneMappingCatalog =
    Import-IntuneMapping `
        -Path $IntuneMappingPath

# ------------------------------------------------------------
# Storage
# ------------------------------------------------------------

$AllSettings     = [System.Collections.ArrayList]::new()
$AllFirewall     = [System.Collections.ArrayList]::new()
$AllUnclassified = [System.Collections.ArrayList]::new()
$Failures        = [System.Collections.ArrayList]::new()
$ParsedGPOs      = [System.Collections.Generic.List[string]]::new()

# ------------------------------------------------------------
# Load XML Files
# ------------------------------------------------------------

$XmlFiles =
    @(
        Get-ChildItem `
            -LiteralPath $XmlFolder `
            -Filter *.xml `
            -File
    )

if ($XmlFiles.Count -lt 1)
{
    throw "No XML files found in: $XmlFolder"
}

Write-Host ""
Write-Host "XML Files Found: $($XmlFiles.Count)"
Write-Host ""

# ------------------------------------------------------------
# Parse Files
# ------------------------------------------------------------

foreach ($XmlFile in $XmlFiles)
{
    Write-Host ""
    Write-Host "================================"
    Write-Host "Processing: $($XmlFile.Name)"
    Write-Host "================================"
    Write-Host ""

    try
    {
        $Result =
            Get-GPOSettingsFromXml `
                -Path $XmlFile.FullName `
                -GPOName $XmlFile.BaseName

        foreach ($Item in $Result.Settings)
        {
            [void]$AllSettings.Add($Item)
        }

        foreach ($Item in $Result.FirewallRules)
        {
            [void]$AllFirewall.Add($Item)
        }

        foreach ($Item in $Result.Unclassified)
        {
            [void]$AllUnclassified.Add($Item)
        }

        $ParsedGPOs.Add($XmlFile.BaseName)

        Write-Host "Settings      : $($Result.Settings.Count)"
        Write-Host "FirewallRules : $($Result.FirewallRules.Count)"
        Write-Host "Unclassified  : $($Result.Unclassified.Count)"

        if ($Result.Unclassified.Count -gt 0)
        {
            Write-Warning "$($XmlFile.BaseName): $($Result.Unclassified.Count) unclassified entries (see $(Get-ReportLocation 'UnclassifiedSettings.csv'))."
        }
    }
    catch
    {
        Write-Warning $_.Exception.Message

        [void]$Failures.Add(
            [PSCustomObject]@{
                GPOName = $XmlFile.BaseName
                Error   = $_.Exception.Message
            }
        )
    }
}

# ------------------------------------------------------------
# Export Raw Parser Output
# ------------------------------------------------------------

$FirewallOutput = @($AllFirewall)

if (
    $null -ne $IntuneMappingCatalog -and
    $null -ne $IntuneMappingCatalog.firewallRuleMapping
)
{
    $FirewallIntuneType = $IntuneMappingCatalog.firewallRuleMapping.intuneType

    $FirewallOutput =
        @(
            $AllFirewall |
            Select-Object *, @{ Name = 'IntuneType'; Expression = { $FirewallIntuneType } }
        )
}

Export-Report $AllSettings     "ParsedSettings.csv"
Export-Report $FirewallOutput  "FirewallRules.csv"
Export-Report $AllUnclassified "UnclassifiedSettings.csv"
Export-Report $Failures        "ParserFailures.csv"

if ($AllSettings.Count -eq 0)
{
    # Write the reports collected so far, so ParserFailures and
    # UnclassifiedSettings are available to see why nothing was parsed.
    if ($ExcelOutput)
    {
        Save-ExcelOutput
    }

    throw "No settings were parsed from any XML file. See $(Get-ReportLocation 'ParserFailures.csv') and $(Get-ReportLocation 'UnclassifiedSettings.csv') in $OutputFolder"
}

# ------------------------------------------------------------
# Build GPO List
# ------------------------------------------------------------

# Every GPO that parsed successfully counts, including one with no settings.
$AllGPOs   = @($ParsedGPOs | Sort-Object -Unique)
$TotalGPOs = $AllGPOs.Count

$GPOsWithSettings = @($AllSettings.GPOName | Sort-Object -Unique)

foreach ($GPO in $AllGPOs)
{
    if ($GPOsWithSettings -notcontains $GPO)
    {
        Write-Warning "$GPO parsed but produced no settings."
    }
}

# ------------------------------------------------------------
# Build Comparison Maps
# ------------------------------------------------------------

$ExactMap = @{}
$NameMap  = @{}

foreach ($Setting in $AllSettings)
{
    $NameKey =
        @(
            $Setting.Class
            $Setting.Extension
            $Setting.Category
            $Setting.SettingName
        ) -join $Sep

    $ExactKey = $NameKey + $Sep + $Setting.Value + $Sep + $Setting.State

    if (-not $ExactMap.ContainsKey($ExactKey))
    {
        $ExactMap[$ExactKey] = @{
            Item = $Setting
            GPOs = [System.Collections.Generic.HashSet[string]]::new()
        }
    }

    [void]$ExactMap[$ExactKey].GPOs.Add($Setting.GPOName)

    if (-not $NameMap.ContainsKey($NameKey))
    {
        $NameMap[$NameKey] = [System.Collections.ArrayList]::new()
    }

    [void]$NameMap[$NameKey].Add($Setting)
}

$SortedExactKeys = @($ExactMap.Keys | Sort-Object)
$SortedNameKeys  = @($NameMap.Keys | Sort-Object)

# Per setting name: how many GPOs configure it, and how many different
# configurations exist across those GPOs. A GPO with several rows for one
# name is treated as one configuration (the set of its values), so multi-row
# settings do not look like conflicts by themselves.

$NameInfo = @{}

foreach ($Key in $SortedNameKeys)
{
    $ByGpo = @{}

    foreach ($Item in $NameMap[$Key])
    {
        if (-not $ByGpo.ContainsKey($Item.GPOName))
        {
            $ByGpo[$Item.GPOName] = [System.Collections.Generic.List[string]]::new()
        }

        $ByGpo[$Item.GPOName].Add($Item.Value + $Sep + $Item.State)
    }

    $Signatures =
        @(
            foreach ($Gpo in $ByGpo.Keys)
            {
                (@($ByGpo[$Gpo] | Sort-Object -Unique)) -join $Sep
            }
        )

    $NameInfo[$Key] = [PSCustomObject]@{
        GpoCount       = $ByGpo.Count
        SignatureCount = @($Signatures | Sort-Object -Unique).Count
    }
}

# ------------------------------------------------------------
# Common Exact
# ------------------------------------------------------------

$CommonSettings =
    @(
        foreach ($Key in $SortedExactKeys)
        {
            $Entry = $ExactMap[$Key]

            if ($Entry.GPOs.Count -eq $TotalGPOs)
            {
                $Entry.Item
            }
        }
    )

# ------------------------------------------------------------
# Common By Name
# ------------------------------------------------------------

$CommonSettingsByName =
    @(
        foreach ($Key in $SortedNameKeys)
        {
            $Info = $NameInfo[$Key]

            if ($Info.GpoCount -eq $TotalGPOs)
            {
                $First = $NameMap[$Key][0]

                [PSCustomObject]@{
                    Class               = $First.Class
                    Extension           = $First.Extension
                    Category            = $First.Category
                    SettingName         = $First.SettingName
                    Value               = $First.Value
                    State               = $First.State
                    SameValueEverywhere = ($Info.SignatureCount -eq 1)
                }
            }
        }
    )

# ------------------------------------------------------------
# Unique (configured in some GPOs, not all)
# ------------------------------------------------------------

$UniqueSettings =
    @(
        foreach ($Key in $SortedNameKeys)
        {
            $Info = $NameInfo[$Key]

            if ($Info.GpoCount -ge $TotalGPOs)
            {
                continue
            }

            $ConfigMap = @{}

            foreach ($Item in $NameMap[$Key])
            {
                $ConfigKey = $Item.Value + $Sep + $Item.State

                if (-not $ConfigMap.ContainsKey($ConfigKey))
                {
                    $ConfigMap[$ConfigKey] = @{
                        Item = $Item
                        GPOs = [System.Collections.Generic.HashSet[string]]::new()
                    }
                }

                [void]$ConfigMap[$ConfigKey].GPOs.Add($Item.GPOName)
            }

            foreach ($ConfigKey in @($ConfigMap.Keys | Sort-Object))
            {
                $Entry = $ConfigMap[$ConfigKey]

                [PSCustomObject]@{
                    Class               = $Entry.Item.Class
                    Extension           = $Entry.Item.Extension
                    Category            = $Entry.Item.Category
                    SettingName         = $Entry.Item.SettingName
                    Value               = $Entry.Item.Value
                    State               = $Entry.Item.State
                    PresentIn           = (@($Entry.GPOs | Sort-Object) -join "; ")
                    ConfiguredInGPOs    = $Info.GpoCount
                    ValuesDiffer        = ($Info.SignatureCount -gt 1)
                }
            }
        }
    )

# ------------------------------------------------------------
# Conflicts (more than one GPO, different configuration)
# ------------------------------------------------------------

$ConflictingSettings =
    @(
        foreach ($Key in $SortedNameKeys)
        {
            $Info = $NameInfo[$Key]

            if ($Info.GpoCount -gt 1 -and $Info.SignatureCount -gt 1)
            {
                $NameMap[$Key] | Sort-Object GPOName
            }
        }
    )

# ------------------------------------------------------------
# Duplicates (more than one GPO, identical configuration)
# ------------------------------------------------------------

$DuplicateSettings =
    @(
        foreach ($Key in $SortedNameKeys)
        {
            $Info = $NameInfo[$Key]

            if ($Info.GpoCount -gt 1 -and $Info.SignatureCount -eq 1)
            {
                $First = $NameMap[$Key][0]
                $Gpos  = @($NameMap[$Key].GPOName | Sort-Object -Unique)

                [PSCustomObject]@{
                    Class       = $First.Class
                    Extension   = $First.Extension
                    Category    = $First.Category
                    SettingName = $First.SettingName
                    Value       = $First.Value
                    State       = $First.State
                    PresentIn   = ($Gpos -join "; ")
                }
            }
        }
    )

# ------------------------------------------------------------
# Deprecated Policy Detection
# ------------------------------------------------------------

$DeprecatedSettings =
    @(
        Get-DeprecatedPolicyMatches `
            -Settings $AllSettings
    )

$DeprecatedLookup = @{}

foreach ($Deprecated in $DeprecatedSettings)
{
    $DeprecatedKey =
        @(
            $Deprecated.GPOName
            $Deprecated.Class
            $Deprecated.Extension
            $Deprecated.Category
            $Deprecated.SettingName
            $Deprecated.Value
        ) -join $Sep

    $DeprecatedLookup[$DeprecatedKey] = $Deprecated
}

# ------------------------------------------------------------
# Missing Matrix
# ------------------------------------------------------------

$Matrix = [System.Collections.Generic.List[object]]::new()

foreach ($Key in $SortedNameKeys)
{
    $Items = $NameMap[$Key]
    $First = $Items[0]

    $Row = [ordered]@{}

    $Row["Setting"] =
        @($First.Class, $First.Extension, $First.Category, $First.SettingName) -join " | "

    foreach ($GPO in $AllGPOs)
    {
        $Row[$GPO] = "Missing"
    }

    foreach ($Item in $Items)
    {
        $Row[$Item.GPOName] = "Present"
    }

    $Matrix.Add([PSCustomObject]$Row)
}

# ------------------------------------------------------------
# Migration Candidates + Intune Mapping
# ------------------------------------------------------------

$MigrationCandidates =
    @(
        foreach ($Setting in $AllSettings)
        {
            $Map = Get-IntuneMapping -Setting $Setting -Catalog $IntuneMappingCatalog

            $DeprecatedKey =
                @(
                    $Setting.GPOName
                    $Setting.Class
                    $Setting.Extension
                    $Setting.Category
                    $Setting.SettingName
                    $Setting.Value
                ) -join $Sep

            $DeprecatedMatch = $DeprecatedLookup[$DeprecatedKey]

            if ($null -eq $IntuneMappingCatalog)
            {
                $MappingStatus = 'MappingFileMissing'
                $Confidence    = 'None'
                $MappingNotes  = 'Intune mapping file was not loaded.'
            }
            elseif ($null -ne $Map)
            {
                $MappingStatus = $Map.mappingStatus
                $Confidence    = $Map.confidence
                $MappingNotes  = $Map.notes
            }
            else
            {
                $MappingStatus = 'Unmapped'
                $Confidence    = 'None'
                $MappingNotes  = 'No matching entry in the Intune mapping file.'
            }

            [PSCustomObject]@{
                GPOName                = $Setting.GPOName
                Class                  = $Setting.Class
                Extension              = $Setting.Extension
                Category               = $Setting.Category
                SettingName            = $Setting.SettingName
                GPOValue               = $Setting.Value
                GPOState               = $Setting.State
                Deprecated             = if ($null -ne $DeprecatedMatch) { 'Yes' } else { 'No' }
                RecommendedReplacement = if ($null -ne $DeprecatedMatch) { $DeprecatedMatch.RecommendedReplacement } else { $null }
                IntuneType             = if ($null -ne $Map) { $Map.intuneType } else { $null }
                IntuneSetting          = if ($null -ne $Map) { $Map.intuneSetting } else { $null }
                OMAURI                 = if ($null -ne $Map) { $Map.omaUri } else { $null }
                MappingStatus          = $MappingStatus
                Confidence             = $Confidence
                Notes                  = $MappingNotes
            }
        }
    )

$UnmappedCount =
    @(
        $MigrationCandidates |
        Where-Object { $_.MappingStatus -in @('Unmapped', 'MappingFileMissing') }
    ).Count

# ------------------------------------------------------------
# Statistics
# ------------------------------------------------------------

$Statistics =
    [PSCustomObject]@{
        Timestamp         = Get-Date
        XmlFiles          = $XmlFiles.Count
        GPOsParsed        = $TotalGPOs
        Settings          = $AllSettings.Count
        FirewallRules     = $AllFirewall.Count
        CommonSettings    = @($CommonSettings).Count
        CommonByName      = @($CommonSettingsByName).Count
        UniqueSettings    = @($UniqueSettings).Count
        Conflicts         = @($ConflictingSettings).Count
        Duplicates        = @($DuplicateSettings).Count
        Deprecated        = $DeprecatedSettings.Count
        UnmappedSettings  = $UnmappedCount
        Unclassified      = $AllUnclassified.Count
        ParseFailures     = $Failures.Count
        MissingSettingsMatrix     = @($Matrix).Count
        IntuneMigrationCandidates = @($MigrationCandidates).Count
    }

# ------------------------------------------------------------
# Export Reports
# ------------------------------------------------------------

Export-Report $CommonSettings        "CommonSettings.csv"
Export-Report $CommonSettingsByName  "CommonSettingsByName.csv"
Export-Report $UniqueSettings        "UniqueSettings.csv"
Export-Report $ConflictingSettings   "ConflictingSettings.csv"
Export-Report $DuplicateSettings     "DuplicateSettings.csv"
Export-Report $DeprecatedSettings    "DeprecatedPolicies.csv"
Export-Report $Matrix                "MissingSettingsMatrix.csv"
Export-Report $MigrationCandidates   "IntuneMigrationCandidates.csv"
Export-Report $Statistics            "RunStatistics.csv"

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

Write-Host ""
Write-Host "Generated Reports"
Write-Host "-----------------"

if ($ExcelOutput)
{
    Save-ExcelOutput
}
else
{
    foreach ($Report in $ExpectedReports)
    {
        $File = Join-Path $OutputFolder "$($FileNamePrefix)$($Report)"

        if (Test-Path -LiteralPath $File)
        {
            Write-Host "[OK] $($FileNamePrefix)$($Report)"
        }
        else
        {
            Write-Warning "$($FileNamePrefix)$($Report) missing"
        }
    }
}

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

Write-Host ""
Write-Host "====================================="
Write-Host "Report Generation Complete"
Write-Host "====================================="
Write-Host ""

if ($Failures.Count -gt 0)
{
    Write-Warning "$($Failures.Count) XML file(s) failed to parse and are excluded from the comparison ($(Get-ReportLocation 'ParserFailures.csv'))."
}

if ($AllUnclassified.Count -gt 0)
{
    Write-Warning "$($AllUnclassified.Count) unclassified entries are not part of the comparison ($(Get-ReportLocation 'UnclassifiedSettings.csv'))."
}

Write-Host "Reports written to:"
Write-Host $OutputFolder
