<#
.SYNOPSIS
    Compare GPO XML exports generated by Get-GPOReport.

.DESCRIPTION
    Processes one or more GPO XML exports and generates comparison, inventory,
    conflict, duplicate, and migration reports.

    XML parsing is performed by GPOCompare.psm1.

    Compare-GPOXml.ps1 is responsible for:

        - Loading XML files
        - Calling Get-GPOSettingsFromXml()
        - Building comparison maps
        - Generating reports
        - Exporting CSV files

.REQUIREMENTS

    GPOCompare.psm1:

        Contains all XML parsing logic.

    IntuneMapping.json (Optional):

        Used to enrich IntuneMigrationCandidates.csv

        If not present, migration report will still be generated.

.INPUTS

    XML reports generated using:

        Get-GPOReport -ReportType Xml

.OUTPUTS

    CommonSettings.csv

        Exact match comparison.

        Setting must have identical:

            Class
            Extension
            Category
            SettingName
            Value
            State

        across every GPO.

    CommonSettingsByName.csv

        Setting appears in every GPO regardless of value.

    UniqueSettings.csv

        Exists in some GPOs but not all.

    ConflictingSettings.csv

        Same setting configured differently across multiple GPOs.

    DuplicateSettings.csv

        Same setting configured identically across multiple GPOs.

    MissingSettingsMatrix.csv

        Presence/absence matrix.

        Example:

            Setting,GPO1,GPO2,GPO3

            PasswordComplexity,
            Present,
            Missing,
            Present

    FirewallRules.csv

        Inventory of firewall rules.

        Firewall rules are intentionally excluded from:

            CommonSettings
            ConflictingSettings
            DuplicateSettings
            UniqueSettings

        to prevent report pollution.

    IntuneMigrationCandidates.csv

        Candidate inventory for migration into Microsoft Intune.

        Optional enrichment comes from:

            IntuneMapping.json

    UnclassifiedSettings.csv

        Parser exceptions and unsupported XML structures.

        Production expectation:

            0 entries

.PARAMETER XmlFolder

    Folder containing XML exports.

.EXAMPLE

    .\Compare-GPOXml.ps1 -XmlFolder "C:\GPOReports" -OutputFolder "C:\GPOReports\Output"

.PARAMETER OutputFolder

    Folder where generated reports will be written.

.PARAMETER ModulePath

    Optional path to GPOCompare.psm1

    Default:

        .\GPOCompare.psm1

.PRODUCTION NOTES

    Recommended directory layout:

        GPO Project

        ├── Compare-GPOXml.ps1
        ├── GPOCompare.psm1
        ├── IntuneMapping.json
        │
        ├── XML
        │
        └── Output

    Recommended module setting:

        $script:ExcludeFirewallRulesFromComparison = $true

    Firewall profile settings are still included in comparison reports.

    Individual firewall rules are exported only to FirewallRules.csv.

.PRODUCTION VALIDATION

    After execution verify:

        UnclassifiedSettings.csv

    should contain:

        0 entries

    Review reports in this order:

        1. ConflictingSettings.csv
        2. DuplicateSettings.csv
        3. UniqueSettings.csv
        4. IntuneMigrationCandidates.csv

.EXPECTED HEALTHY OUTPUT

    Example:

        Settings      : 180+
        FirewallRules : 200+
        Unclassified  : 0

.AUTHOR

    Siconic

.VERSION

    1.0

#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$XmlFolder,

    [Parameter(Mandatory)]
    [string]$OutputFolder,

    [string]$ModulePath = ".\GPOCompare.psm1"
)

$ErrorActionPreference = "Stop"

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

if (-not (Test-Path $XmlFolder))
{
    throw "XML folder not found: $XmlFolder"
}

if (-not (Test-Path $OutputFolder))
{
    New-Item `
        -Path $OutputFolder `
        -ItemType Directory `
        -Force | Out-Null
}

if (-not (Test-Path $ModulePath))
{
    throw "Module not found: $ModulePath"
}

# ------------------------------------------------------------
# Load Module
# ------------------------------------------------------------

Import-Module $ModulePath -Force

# ------------------------------------------------------------
# Deprecated Policy Reference
# ------------------------------------------------------------

$DeprecatedReferenceFile =
    Join-Path `
        $PSScriptRoot `
        "DeprecatedPoliciesReference.md"

Import-DeprecatedPolicyReference `
    -Path $DeprecatedReferenceFile

# ------------------------------------------------------------
# Storage
# ------------------------------------------------------------

$AllSettings     = [System.Collections.ArrayList]::new()
$AllFirewall     = [System.Collections.ArrayList]::new()
$AllUnclassified = [System.Collections.ArrayList]::new()
$Failures        = [System.Collections.ArrayList]::new()

# ------------------------------------------------------------
# Load XML Files
# ------------------------------------------------------------

$XmlFiles =
    Get-ChildItem `
        -Path $XmlFolder `
        -Filter *.xml

if ($XmlFiles.Count -lt 1)
{
    throw "No XML files found."
}

Write-Host ""
Write-Host "XML Files Found: $($XmlFiles.Count)"
Write-Host ""

# ------------------------------------------------------------
# Parse Files
# ------------------------------------------------------------

foreach ($XmlFile in $XmlFiles)
{
    Write-Host ""
    Write-Host "================================"
    Write-Host "Processing: $($XmlFile.Name)"
    Write-Host "================================"
    Write-Host ""

    try
    {
        $Result =
            Get-GPOSettingsFromXml `
                -Path $XmlFile.FullName `
                -GPOName $XmlFile.BaseName

        foreach ($Item in $Result.Settings)
        {
            [void]$AllSettings.Add($Item)
        }

        foreach ($Item in $Result.FirewallRules)
        {
            [void]$AllFirewall.Add($Item)
        }

        foreach ($Item in $Result.Unclassified)
        {
            [void]$AllUnclassified.Add($Item)
        }

        Write-Host "Settings      : $($Result.Settings.Count)"
        Write-Host "FirewallRules : $($Result.FirewallRules.Count)"
        Write-Host "Unclassified  : $($Result.Unclassified.Count)"
    }
    catch
    {
        Write-Warning $_.Exception.Message

        [void]$Failures.Add(
            [PSCustomObject]@{
                GPOName = $XmlFile.BaseName
                Error   = $_.Exception.Message
            }
        )
    }
}

# ------------------------------------------------------------
# Export Raw Parser Output
# ------------------------------------------------------------

$AllSettings |
Export-Csv (
    Join-Path $OutputFolder "ParsedSettings.csv"
) -NoTypeInformation

$AllFirewall |
Export-Csv (
    Join-Path $OutputFolder "FirewallRules.csv"
) -NoTypeInformation

$AllUnclassified |
Export-Csv (
    Join-Path $OutputFolder "UnclassifiedSettings.csv"
) -NoTypeInformation

$Failures |
Export-Csv (
    Join-Path $OutputFolder "ParserFailures.csv"
) -NoTypeInformation

# ------------------------------------------------------------
# Build GPO List
# ------------------------------------------------------------

$AllGPOs =
    $AllSettings.GPOName |
    Sort-Object -Unique

$TotalGPOs =
    @($AllGPOs).Count

# ------------------------------------------------------------
# Build Comparison Maps
# ------------------------------------------------------------

$ExactMap = @{}
$NameMap  = @{}

foreach ($Setting in $AllSettings)
{
    $ExactKey = @(
        $Setting.Class
        $Setting.Extension
        $Setting.Category
        $Setting.SettingName
        $Setting.Value
        $Setting.State
    ) -join "|"

    $NameKey = @(
        $Setting.Class
        $Setting.Extension
        $Setting.Category
        $Setting.SettingName
    ) -join "|"

    if (-not $ExactMap.ContainsKey($ExactKey))
    {
        $ExactMap[$ExactKey] = @{
            Item = $Setting
            GPOs = [System.Collections.Generic.HashSet[string]]::new()
        }
    }

    $null =
        $ExactMap[$ExactKey].GPOs.Add(
            $Setting.GPOName
        )

    if (-not $NameMap.ContainsKey($NameKey))
    {
        $NameMap[$NameKey] =
            [System.Collections.ArrayList]::new()
    }

    [void]$NameMap[$NameKey].Add($Setting)
}

# ------------------------------------------------------------
# Common Exact
# ------------------------------------------------------------

$CommonSettings =
foreach ($Key in $ExactMap.Keys)
{
    $Item = $ExactMap[$Key]

    if ($Item.GPOs.Count -eq $TotalGPOs)
    {
        $Item.Item
    }
}

# ------------------------------------------------------------
# Common By Name
# ------------------------------------------------------------

$CommonSettingsByName =
foreach ($Key in $NameMap.Keys)
{
    $Items = $NameMap[$Key]

    $DistinctGPOs =
        $Items.GPOName |
        Sort-Object -Unique

    if (@($DistinctGPOs).Count -eq $TotalGPOs)
    {
        $Items[0]
    }
}

# ------------------------------------------------------------
# Unique
# ------------------------------------------------------------

$UniqueSettings =
foreach ($Key in $ExactMap.Keys)
{
    $Item = $ExactMap[$Key]

    if ($Item.GPOs.Count -lt $TotalGPOs)
    {
        [PSCustomObject]@{
            Class       = $Item.Item.Class
            Extension   = $Item.Item.Extension
            Category    = $Item.Item.Category
            SettingName = $Item.Item.SettingName
            Value       = $Item.Item.Value
            State       = $Item.Item.State
            PresentIn   = ($Item.GPOs -join "; ")
        }
    }
}

# ------------------------------------------------------------
# Conflicts
# ------------------------------------------------------------

$ConflictingSettings =
foreach ($Key in $NameMap.Keys)
{
    $Items = $NameMap[$Key]

    $Configs =
        $Items |
        Select-Object Value,State -Unique

    if (@($Configs).Count -gt 1)
    {
        $Items
    }
}

# ------------------------------------------------------------
# Duplicates
# ------------------------------------------------------------

$DuplicateSettings =
foreach ($Key in $NameMap.Keys)
{
    $Items = $NameMap[$Key]

    $Configs =
        $Items |
        Select-Object Value,State -Unique

    if (@($Configs).Count -eq 1)
    {
        $DistinctGPOs =
            $Items.GPOName |
            Sort-Object -Unique

        if (@($DistinctGPOs).Count -gt 1)
        {
            $Items[0]
        }
    }
}

# ------------------------------------------------------------
# Deprecated Policy Detection
# ------------------------------------------------------------

$DeprecatedSettings =
    Get-DeprecatedPolicyMatches `
        -Settings $AllSettings

# ------------------------------------------------------------
# Missing Matrix
# ------------------------------------------------------------

$Matrix = @()

foreach ($Key in $NameMap.Keys)
{
    $Items = $NameMap[$Key]

    $Row = [ordered]@{}

    $Row["Setting"] = $Key

    foreach ($GPO in $AllGPOs)
    {
        $Row[$GPO] = "Missing"
    }

    foreach ($Item in $Items)
    {
        $Row[$Item.GPOName] = "Present"
    }

    $Matrix += [PSCustomObject]$Row
}

# ------------------------------------------------------------
# Migration Candidates
# ------------------------------------------------------------

$MigrationCandidates =
$AllSettings |
Select-Object `
    GPOName,
    Class,
    Extension,
    Category,
    SettingName,
    Value,
    State

# ------------------------------------------------------------
# Statistics
# ------------------------------------------------------------

$Statistics =
    [PSCustomObject]@{

        Timestamp =
            Get-Date

        XmlFiles =
            $XmlFiles.Count

        Settings =
            $AllSettings.Count

        FirewallRules =
            $AllFirewall.Count

        CommonSettings =
            $CommonSettings.Count

        CommonByName =
            $CommonSettingsByName.Count

        UniqueSettings =
            $UniqueSettings.Count

        Conflicts =
            $ConflictingSettings.Count

        Duplicates =
            $DuplicateSettings.Count

        Deprecated =
            @($DeprecatedSettings).Count

        Unclassified =
            $AllUnclassified.Count

        ParseFailures =
            $Failures.Count
    }

# ------------------------------------------------------------
# Export Reports
# ------------------------------------------------------------

$CommonSettings |
Export-Csv (
    Join-Path $OutputFolder "CommonSettings.csv"
) -NoTypeInformation

$CommonSettingsByName |
Export-Csv (
    Join-Path $OutputFolder "CommonSettingsByName.csv"
) -NoTypeInformation

$UniqueSettings |
Export-Csv (
    Join-Path $OutputFolder "UniqueSettings.csv"
) -NoTypeInformation

$ConflictingSettings |
Export-Csv (
    Join-Path $OutputFolder "ConflictingSettings.csv"
) -NoTypeInformation

$DuplicateSettings |
Export-Csv (
    Join-Path $OutputFolder "DuplicateSettings.csv"
) -NoTypeInformation

$DeprecatedSettings |
Export-Csv (
    Join-Path $OutputFolder "DeprecatedPolicies.csv"
) -NoTypeInformation

$Matrix |
Export-Csv (
    Join-Path $OutputFolder "MissingSettingsMatrix.csv"
) -NoTypeInformation

$MigrationCandidates |
Export-Csv (
    Join-Path $OutputFolder "IntuneMigrationCandidates.csv"
) -NoTypeInformation

$Statistics |
Export-Csv (
    Join-Path $OutputFolder "RunStatistics.csv"
) -NoTypeInformation

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

$ExpectedReports = @(
    "ParsedSettings.csv"
    "CommonSettings.csv"
    "CommonSettingsByName.csv"
    "UniqueSettings.csv"
    "ConflictingSettings.csv"
    "DuplicateSettings.csv"
    "DeprecatedPolicies.csv"
    "MissingSettingsMatrix.csv"
    "FirewallRules.csv"
    "IntuneMigrationCandidates.csv"
    "UnclassifiedSettings.csv"
    "RunStatistics.csv"
)

Write-Host ""
Write-Host "Generated Reports"
Write-Host "-----------------"

foreach ($Report in $ExpectedReports)
{
    $File =
        Join-Path $OutputFolder $Report

    if (Test-Path $File)
    {
        Write-Host "[OK] $Report"
    }
    else
    {
        Write-Warning "$Report missing"
    }
}

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

Write-Host ""
Write-Host "====================================="
Write-Host "Report Generation Complete"
Write-Host "====================================="
Write-Host ""

Write-Host "Common Exact      : $($CommonSettings.Count)"
Write-Host "Common By Name    : $($CommonSettingsByName.Count)"
Write-Host "Unique            : $($UniqueSettings.Count)"
Write-Host "Conflicting       : $($ConflictingSettings.Count)"
Write-Host "Duplicate         : $($DuplicateSettings.Count)"
Write-Host "Firewall Rules    : $($AllFirewall.Count)"
Write-Host "Deprecated        : $(@($DeprecatedSettings).Count)"
Write-Host "Unclassified      : $($AllUnclassified.Count)"
Write-Host ""

Write-Host "Reports written to:"
Write-Host $OutputFolder
